import type { HeartTuneMaterial } from './types'

export const heartTuneMaterials: readonly HeartTuneMaterial[] = [
  {
    "id": "flirt-directed-001",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "亲吻锁骨",
    "text": "玩家靠向伴侣，在伴侣锁骨凹陷处连续亲吻30秒。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-002",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "褪去外套",
    "text": "玩家用双手解开伴侣上衣纽扣，将其外套缓慢脱下。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-003",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "揉捏后颈",
    "text": "大大怪用手掌贴住小怪兽后颈，轻轻揉捏60秒。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-004",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "亲吻手腕",
    "text": "小怪兽拉起大大怪的手，在手腕内侧亲吻15秒。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-005",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "指尖划腰",
    "text": "玩家用食指隔着衣服，在伴侣腰侧来回划拉30秒。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-006",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "脱掉鞋袜",
    "text": "玩家让伴侣坐在床沿，亲手为伴侣脱下鞋子和袜子。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-007",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "抚摸头发",
    "text": "大大怪用手穿过小怪兽的头发，轻抚头皮30秒。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-008",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "亲吻侧脸",
    "text": "小怪兽凑近大大怪，在他的左侧脸颊用力亲吻两下。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-009",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "耳后吹气",
    "text": "玩家凑近伴侣的耳后敏感区，轻轻吹气10秒。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-010",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "捏脸对视",
    "text": "大大怪捏住小怪兽的下巴抬起，直视她的眼睛30秒。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-011",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "掌心画圈",
    "text": "小怪兽拉过大大怪的手掌，用指腹在掌心画圈30秒。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-012",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "抚摸脸颊",
    "text": "玩家用双手捧起伴侣的脸颊，用大拇指轻轻摩挲30秒。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-013",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "咬红耳朵",
    "text": "大大怪凑近小怪兽的右耳，轻轻咬住耳垂拉扯3秒。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-014",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "亲吻指尖",
    "text": "小怪兽举起大大怪的手，依次亲吻他的五根手指。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-015",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "额头轻吻",
    "text": "玩家按住伴侣的双肩，低头在伴侣额头上留下长吻。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-016",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "解开领带",
    "text": "小怪兽双手抓住大大怪的领带或衣领，慢慢往下拉。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-017",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "抚摸喉结",
    "text": "小怪兽伸出手指，在大大怪的喉结上轻轻滑动15秒。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-018",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "摘下首饰",
    "text": "玩家伸手解开伴侣的手表或项链，放到旁边的桌子上。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-019",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "揉捏肩膀",
    "text": "大大怪站在小怪兽身后，双手用力揉捏她的双肩60秒。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-020",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "鼻尖轻蹭",
    "text": "玩家把脸凑近伴侣，用自己的鼻尖蹭对方的鼻尖15秒。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-021",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "隔衣抚背",
    "text": "小怪兽双手环抱大大怪，隔着衣服在他的背部上下抚摸。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-022",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "亲吻脖颈",
    "text": "大大怪拨开小怪兽的头发，在她的脖颈侧边亲吻15秒。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-023",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "扯掉发圈",
    "text": "玩家伸手解开伴侣的发圈，用手拨弄让头发自然散落。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-024",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "指刮下颌",
    "text": "小怪兽用食指指节，顺着大大怪的下颌线慢慢刮动3次。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-directed-025",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "轻点嘴唇",
    "text": "玩家用大拇指指腹，在伴侣的嘴唇上轻轻按压摩擦3次。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-026",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "耳边吹气",
    "text": "玩家在伴侣耳边吹气，伴侣立刻回吻玩家侧脸。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-027",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "脸颊贴合",
    "text": "小怪兽贴住大大怪脸颊摩擦，大大怪伸手抱紧她的腰。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-028",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "触碰耳朵",
    "text": "玩家用手指捏伴侣耳垂，伴侣低头靠在玩家肩上。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-029",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "解开衣扣",
    "text": "大大怪解开小怪兽衣领扣子，小怪兽抬头亲吻他下巴。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-030",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "喂食糖果",
    "text": "玩家把糖果放在嘴唇中间，伴侣靠过来用嘴接走。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-031",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "手心写字",
    "text": "小怪兽在大大怪手心画圈，大大怪顺势亲吻她的额头。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-032",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "拉扯衣角",
    "text": "玩家伸手拉扯伴侣的衣角，伴侣顺势靠近抱住玩家。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-033",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "蒙眼猜测",
    "text": "大大怪用手蒙住小怪兽眼睛，小怪兽伸手摸他的脸颊。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-034",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "递上水杯",
    "text": "玩家喝一口水递给伴侣，伴侣就着同一个杯口喝下。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-035",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "张开双臂",
    "text": "小怪兽向大大怪张开双手，大大怪立刻上前紧紧拥抱。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-036",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "触碰锁骨",
    "text": "玩家手指点在伴侣锁骨上，伴侣低头亲吻玩家的手背。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-037",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "轻咬手指",
    "text": "大大怪把食指放在小怪兽唇边，小怪兽张嘴轻轻咬住。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-038",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "捧脸对视",
    "text": "玩家捧起伴侣的脸对视，伴侣需主动闭上眼睛等待。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-039",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "抚摸后颈",
    "text": "小怪兽轻抚大大怪后颈，大大怪顺势低头埋进她颈窝。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-040",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "凑近颈窝",
    "text": "玩家把脸埋进伴侣颈窝深呼吸，伴侣伸手抚摸玩家后背。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-041",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "指尖对碰",
    "text": "大大怪伸出食指，小怪兽也伸出食指与他指尖相触摩擦。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-042",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "扯开领口",
    "text": "玩家稍微扯开自己的领口，伴侣靠过来在锁骨上亲吻。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-043",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "抚摸膝盖",
    "text": "大大怪把手放在小怪兽膝盖上，小怪兽用双手覆盖他手背。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-044",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "闭眼靠近",
    "text": "小怪兽闭上眼睛微微仰头，大大怪低头亲吻她的嘴唇。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-045",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "捏住脸颊",
    "text": "玩家轻轻捏住伴侣脸颊两边，伴侣被迫嘟嘴并被亲一口。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-046",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "搂住腰肢",
    "text": "大大怪伸手搂住小怪兽的腰，小怪兽顺势贴紧他的胸膛。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-047",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "靠上肩膀",
    "text": "玩家主动把头靠在伴侣肩膀上，伴侣侧头亲吻玩家头顶。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-048",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "手指梳头",
    "text": "小怪兽用手指给大大怪梳理头发，大大怪闭上眼睛靠过去。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-049",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "拍打身旁",
    "text": "玩家拍拍自己身边的空位，伴侣走过去紧挨着大腿坐下。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-response-050",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "轻碰鼻尖",
    "text": "大大怪用鼻尖碰小怪兽鼻尖，小怪兽轻咬他的下嘴唇。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-051",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "十指紧扣",
    "text": "两人双手十指交叉紧扣，放在胸前对视60秒。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-052",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "额头相抵",
    "text": "两人额头贴着额头，闭上眼睛平复呼吸30秒。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-053",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "嘴对嘴喂",
    "text": "两人不用手，只用嘴唇互相传递吃下一颗糖果。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-054",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "拥抱深吸",
    "text": "两人站立紧紧拥抱，互相在对方颈窝深呼吸30秒。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-055",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互揉肩膀",
    "text": "两人面对面站立，互相用双手揉捏对方的肩膀30秒。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-056",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "鼻尖互蹭",
    "text": "两人闭上眼睛，用鼻尖互相蹭对方的脸颊和鼻子30秒。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-057",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互相喂水",
    "text": "两人各拿一杯水，同时把水杯递到对方嘴边喂给对方。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-058",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "紧贴心跳",
    "text": "两人隔着衣服胸膛紧贴，闭眼感受对方的心跳60秒。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-059",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互脱外套",
    "text": "两人同时伸出手，帮对方脱下最外层的一件衣服。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-060",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "呼吸同频",
    "text": "两人脸贴脸相距不到三厘米，调整呼吸直到完全一致。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-061",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "对视憋笑",
    "text": "两人相隔一臂距离站立对视，谁先笑出来就要亲对方一下。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-062",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互理头发",
    "text": "两人同时伸出双手，帮对方整理有些凌乱的头发。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-063",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "掌心互击",
    "text": "两人像玩游戏一样双手击掌，然后十指相扣停住15秒。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-064",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "交叠双手",
    "text": "两人把手掌一层层叠在一起，用力压紧保持15秒。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-065",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "隔衣蹭腰",
    "text": "两人面对面拥抱，用自己的腰部隔衣摩擦对方的腰部30秒。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-066",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互吻手背",
    "text": "两人同时抬起对方的右手，低头在对方手背上亲吻。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-067",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "左右贴面",
    "text": "两人像礼仪一样，互相贴一下左右脸颊并亲一口。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-068",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "交换呼吸",
    "text": "两人张开嘴唇靠近，不碰到对方只互相呼吸对方的空气。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-069",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "闭眼互摸",
    "text": "两人闭上眼睛，只用双手摸索对方的脸部轮廓30秒。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-070",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互扯衣角",
    "text": "两人互相抓住对方的衣角往下扯，拉近彼此的距离。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-071",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互捏耳垂",
    "text": "两人同时伸出手，捏住对方的右耳垂轻轻揉搓15秒。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-072",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "眼神拉丝",
    "text": "两人在脱去鞋袜的过程中，全程保持眼神对视不躲闪。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-073",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "肩并肩坐",
    "text": "两人紧紧挨着肩膀并排坐下，大腿外侧互相贴紧30秒。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-074",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互碰膝盖",
    "text": "两人面对面坐着，双腿交错互相碰触对方的膝盖内侧。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-duo-075",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "轻啄嘴唇",
    "text": "两人快速在对方嘴唇上连亲三下，马上分开。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-076",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "沙发拥抱",
    "text": "两人在沙发上侧坐，玩家把伴侣抱在怀里30秒。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-077",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "墙边对视",
    "text": "大大怪把小怪兽按在墙边，低头对视30秒不许笑。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-078",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "床沿脱袜",
    "text": "玩家坐在床沿，伴侣蹲下为玩家脱掉双脚的袜子。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-079",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "门后轻吻",
    "text": "两人站在门后，玩家把伴侣抵在门板上亲吻嘴唇30秒。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-080",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "镜前整理",
    "text": "两人站在穿衣镜前，大大怪从背后帮小怪兽整理衣领。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-081",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "地毯并坐",
    "text": "两人在地毯上并排靠墙坐下，小怪兽把头靠在大大怪肩上。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-082",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "椅子背后",
    "text": "小怪兽坐在椅子上，大大怪站在背后低头亲吻她的头发。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-083",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "餐桌搂腰",
    "text": "大大怪靠在餐桌边，小怪兽走过去双手环抱他的腰。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-084",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "床上侧看",
    "text": "小怪兽仰躺在床上，大大怪侧躺在旁边单手撑头看着她。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-085",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "沙发跨坐",
    "text": "大大怪靠坐沙发，小怪兽穿着衣服跨坐在他腿上面对面。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-086",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "窗前背抱",
    "text": "两人站在窗前看风景，大大怪从背后搂住小怪兽的肩膀。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-087",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "浴室门框",
    "text": "玩家靠在浴室门框上，伴侣走过去双手捧住玩家的脸亲吻。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-088",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "梳妆台前",
    "text": "小怪兽坐在梳妆台前，大大怪拿梳子帮她梳理头发60秒。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-089",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "床铺中央",
    "text": "两人在床中央面对面盘腿坐，十指紧扣轻轻摇晃30秒。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-090",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "冰箱门前",
    "text": "大大怪打开冰箱，小怪兽从背后贴上去抱住他的背。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-091",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "洗手台边",
    "text": "两人站在洗手台前，玩家用湿毛巾帮伴侣擦手背和手腕。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-092",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "衣柜门前",
    "text": "玩家站在衣柜前，伴侣走过去在玩家后颈快速亲一口。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-093",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "沙发扶手",
    "text": "小怪兽坐在沙发扶手上，捏住站着的大大怪脸颊对视。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-094",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "书桌旁边",
    "text": "大大怪坐在书桌前，小怪兽站到旁边把下巴搁在他肩膀上。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-095",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "地板平躺",
    "text": "两人在地毯上并排平躺，转过头看着对方的侧脸30秒。",
    "rolePolicy": "none",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-096",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "走廊挡路",
    "text": "玩家双手撑住走廊墙壁挡路，伴侣必须亲玩家一口才能过。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-097",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "床尾地毯",
    "text": "小怪兽趴在床尾地毯上，大大怪坐在旁边揉捏她的小腿。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-098",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "墙角贴胸",
    "text": "大大怪背靠墙角，小怪兽上前一步贴紧他的胸膛深呼吸。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-099",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "换鞋凳上",
    "text": "玩家坐在换鞋凳上，伴侣半蹲下帮玩家解开鞋带并脱下鞋。",
    "rolePolicy": "dynamic",
    "source": "一阶段.txt"
  },
  {
    "id": "flirt-scene-100",
    "stage": "flirt",
    "stageLabel": "调情",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "飘窗台面",
    "text": "两人在飘窗上面对面坐下，大大怪低头亲吻小怪兽的手心。",
    "rolePolicy": "fixed",
    "source": "一阶段.txt"
  },
  {
    "id": "foreplay-directed-001",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "褪去上衣",
    "text": "玩家双手抓住伴侣贴身上衣下摆，向上完全脱掉。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-002",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "冰块游走",
    "text": "小怪兽拿一块冰，在大大怪赤裸的胸膛上缓慢滑动30秒。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-003",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "隔衣揉捏",
    "text": "大大怪隔着内衣，用手掌揉捏小怪兽的腰侧30秒。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-004",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "眼罩遮蔽",
    "text": "玩家用眼罩蒙住伴侣眼睛，在伴侣大腿上轻抚60秒。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-005",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "亲吻胸沟",
    "text": "大大怪低头，在小怪兽的胸沟处连续亲吻30秒。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-006",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "解开内衣",
    "text": "玩家走到伴侣身后，单手解开伴侣背后的内衣搭扣。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-007",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "抚摸大腿",
    "text": "小怪兽用双手从大大怪的膝盖，一路向上抚摸到大腿根。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-008",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "舔舐耳廓",
    "text": "大大怪含住小怪兽的耳廓，用舌尖仔细舔舐15秒。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-009",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "乳液推背",
    "text": "玩家把乳液倒在掌心搓热，用力推拿伴侣的后背60秒。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-010",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "丝带蒙眼",
    "text": "小怪兽用一条软丝带，从脑后将大大怪的眼睛蒙住。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-011",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "咬拉肩带",
    "text": "大大怪用牙齿咬住小怪兽的内衣肩带，向外拉扯后松开。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-012",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "抚摸腹肌",
    "text": "玩家解开伴侣裤扣，将手伸进边缘抚摸伴侣的下腹部30秒。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-013",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "亲吻脊柱",
    "text": "小怪兽顺着大大怪的脊柱，从脖颈一路向下亲吻到腰窝。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-014",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "揉捏胸部",
    "text": "大大怪隔着内衣，用双手大面积揉捏小怪兽的胸部30秒。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-015",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "冰块贴唇",
    "text": "玩家把冰块贴在自己唇上，再去亲吻伴侣的侧颈15秒。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-016",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "褪去长裤",
    "text": "玩家解开伴侣腰带，将伴侣的长裤拉到脚踝处完全脱下。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-017",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "指划腿根",
    "text": "大大怪用食指指甲，在小怪兽的大腿内侧轻轻刮划30秒。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-018",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "吮吸锁骨",
    "text": "小怪兽用力吮吸大大怪的锁骨，留下一个清晰的红印。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-019",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "抚摸臀线",
    "text": "玩家将双手伸进伴侣裤腰边缘，顺着臀部曲线抚摸30秒。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-020",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "湿吻脖颈",
    "text": "大大怪张开嘴唇，在小怪兽脖颈大动脉处深吸吮15秒。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-021",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "褪去裙子",
    "text": "大大怪拉开小怪兽裙子拉链，顺着大腿将其完全褪下。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-022",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "揉捏大腿",
    "text": "小怪兽双手握住大大怪的大腿内侧肌肉，用力揉捏30秒。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-023",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "羽毛挑逗",
    "text": "玩家拿一根羽毛，在伴侣裸露的腰腹上来回扫动30秒。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-024",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "亲吻肚脐",
    "text": "大大怪半跪在小怪兽身前，低头亲吻她的肚脐周围15秒。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-directed-025",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "隔裤摩擦",
    "text": "小怪兽将手掌覆盖在大大怪大腿根部的裤子上按压摩擦。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-026",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "亲吻胸口",
    "text": "大大怪亲吻小怪兽胸口，小怪兽用双手按住他的后脑勺。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-027",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "涂抹乳液",
    "text": "玩家在伴侣背部涂抹乳液，伴侣出声确认力度大小。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-028",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "抚摸腹部",
    "text": "小怪兽抚摸大大怪下腹，大大怪低头亲吻她的锁骨。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-029",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "丝带捆绑",
    "text": "玩家用丝带绑住伴侣双手，伴侣主动抬起双臂配合动作。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-030",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "解开裤扣",
    "text": "大大怪解开小怪兽裤扣，小怪兽主动抬腰方便脱下长裤。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-031",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "隔衣触碰",
    "text": "玩家手伸进伴侣衣服下摆，伴侣大口喘气回应抚摸。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-032",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "索要深吻",
    "text": "玩家手指按压伴侣下唇，伴侣立刻张嘴回应法式深吻。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-033",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "抚摸引导",
    "text": "伴侣握住玩家的手，拖到自己目前最想被摸的腰侧。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-034",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "轻咬肩膀",
    "text": "小怪兽用力咬大大怪的肩膀，大大怪伸手搂紧她的腰。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-035",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "捏住下巴",
    "text": "大大怪捏住小怪兽下巴接吻，小怪兽双手环抱他脖子。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-036",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "顺延亲吻",
    "text": "玩家从小腿向上亲吻到大腿，伴侣微微分开双腿配合。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-037",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "按压腰窝",
    "text": "大大怪用力按压小怪兽腰窝，小怪兽顺势向后贴紧他。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-038",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "抚摸臀部",
    "text": "玩家双手揉捏伴侣的臀部，伴侣主动向玩家怀里靠紧。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-039",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "冰块刺激",
    "text": "小怪兽把冰水滴在大大怪胸口，大大怪立刻伸手抱紧她。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-040",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "摘下眼罩",
    "text": "玩家帮伴侣摘下眼罩，伴侣睁眼后立刻亲吻玩家嘴唇。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-041",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "靠近锁骨",
    "text": "大大怪脸埋在小怪兽锁骨处，小怪兽伸手抚摸他头发。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-042",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "扯落肩带",
    "text": "玩家扯下伴侣一侧的内衣肩带，伴侣低头吻玩家手背。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-043",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "贴胸摩擦",
    "text": "小怪兽用胸口摩擦大大怪，大大怪双手托住她的背部。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-044",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "抚摸大腿",
    "text": "玩家双手游走在伴侣大腿，伴侣大声说出痒或爽的位置。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-045",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "脱去内衣",
    "text": "大大怪脱下小怪兽内衣，小怪兽用双手遮住胸口15秒。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-046",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "咬拉衣角",
    "text": "玩家用牙齿咬住伴侣衣角拉扯，伴侣顺势脱去这件衣服。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-047",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "按摩小腿",
    "text": "大大怪揉捏小怪兽小腿肌肉，小怪兽用脚趾蹭他大腿。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-048",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "贴近喘息",
    "text": "小怪兽在大大怪耳边深喘息，大大怪转头狠狠吻住她。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-049",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "后背画圈",
    "text": "玩家在伴侣赤裸的后背画圈，伴侣大声说出被碰的位置。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-response-050",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "解开皮带",
    "text": "小怪兽解开大大怪的皮带抽走，大大怪按住她的双手。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-051",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "半裸相拥",
    "text": "两人脱去全部上衣，胸膛完全贴合在一起拥抱60秒。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-052",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互褪底裤",
    "text": "两人互相动手，帮对方缓慢褪去最外层的长裤或短裙。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-053",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互相揉臀",
    "text": "两人面对面站立拥抱，同时用力揉捏对方的臀部30秒。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-054",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "舌尖纠缠",
    "text": "两人张开嘴唇，进行长达60秒的深吻，手抚摸对方腰背。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-055",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互解纽扣",
    "text": "两人同时伸出手，一颗颗解开对方衬衫或外套的纽扣。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-056",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "胸膛互贴",
    "text": "两人脱去上衣，用胸膛紧紧贴紧对方，缓慢左右摩擦。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-057",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互摸大腿",
    "text": "两人面对面坐着，双手伸进对方的裤管抚摸大腿30秒。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-058",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "冰火交替",
    "text": "一人含温水一人含冰水，交替亲吻对方的脖颈和肩膀。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-059",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互咬耳垂",
    "text": "两人侧头靠在对方肩膀，互相轻咬拉扯对方的耳垂15秒。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-060",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "同步呼吸",
    "text": "两人赤裸上半身贴紧，随着深呼吸感受胸膛的起伏30秒。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-061",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互抹乳液",
    "text": "两人双手沾满润滑乳液，互相在对方后背打圈推拿。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-062",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "交叠抚背",
    "text": "两人紧紧抱在一起，双手在对方裸露的背部大面积游走。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-063",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互相摩擦",
    "text": "两人隔着最后的外裤，用下半身紧贴着来回缓慢摩擦。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-064",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互吻锁骨",
    "text": "两人同时低头，在对方的锁骨位置用力吸出红印。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-065",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "十指扣头",
    "text": "两人接吻时，双手十指交叉按在对方的后脑勺上施压。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-066",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "大腿交缠",
    "text": "两人面对面侧躺，将双腿互相交缠锁死，感受肌肤贴合。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-067",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互解皮带",
    "text": "两人同时把手伸向对方腰间，解开对方的皮带抽掉。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-068",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互探衣摆",
    "text": "两人同时把手探入对方上衣下摆，用力抚摸腰部肌肤。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-069",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "唇齿交握",
    "text": "两人闭眼张嘴深吻，互相用力吸吮对方的舌尖30秒。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-070",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "额头对撞",
    "text": "两人接吻后额头抵着额头，双手互相捧着对方的侧脸。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-071",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互捏腰窝",
    "text": "两人同时伸手探到对方身后，用力按揉对方的腰窝。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-072",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "蒙眼互摸",
    "text": "两人都戴上眼罩，仅靠双手摸索对方裸露的肌肤60秒。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-073",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互扯衣领",
    "text": "两人抓着对方衣领拉近距离，张开嘴互吹对方的脸颊。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-074",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互量腰围",
    "text": "两人用双手环绕对方的腰，丈量并用指腹滑过腰线30秒。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-duo-075",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "胸口画圈",
    "text": "两人同时用一根手指，在对方赤裸的胸口慢慢画圈。",
    "rolePolicy": "none",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-076",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "沙发半躺",
    "text": "小怪兽在沙发半躺，大大怪压上去亲吻脖颈60秒。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-077",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "椅子跨坐",
    "text": "大大怪坐在椅子上，小怪兽跨坐他腿上隔衣摩擦30秒。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-078",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "桌边亲吻",
    "text": "小怪兽靠在桌边，大大怪双手扶住她的腰深吻60秒。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-079",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "地毯揉背",
    "text": "大大怪趴在地毯上，小怪兽坐在他腰上揉捏赤裸后背。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-080",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "穿衣镜前",
    "text": "两人站在镜前，大大怪从背后解开小怪兽的内衣搭扣。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-081",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "床沿站立",
    "text": "小怪兽站在床沿，大大怪单膝跪在床边亲吻她的大腿。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-082",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "浴室门后",
    "text": "大大怪把小怪兽按在浴室门后，伸手探进她裙底边缘。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-083",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "沙发角落",
    "text": "小怪兽缩在沙发角落，大大怪拿冰块在她锁骨滑动。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-084",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "靠墙脱衣",
    "text": "玩家背靠卧室墙壁，伴侣单手将玩家上衣完全扯下。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-085",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "餐桌坐边",
    "text": "小怪兽坐在餐桌边缘，大大怪站在双腿间亲吻她侧颈。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-086",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "床头靠垫",
    "text": "大大怪靠坐在床头，小怪兽跪在他身边亲吻他的胸肌。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-087",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "飘窗平躺",
    "text": "小怪兽平躺在飘窗上，大大怪双手抚摸她露出的腰腹。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-088",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "洗手台上",
    "text": "大大怪把小怪兽抱上洗手台，脱下她的外裤亲吻脚踝。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-089",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "换鞋凳前",
    "text": "大大怪坐在换鞋凳上，小怪兽跨站着低头深吻他30秒。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-090",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "电脑椅上",
    "text": "小怪兽坐在电脑椅上，大大怪按住扶手亲吻她大腿内侧。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-091",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "地毯抱坐",
    "text": "大大怪盘腿坐在地毯上，小怪兽面对面跨坐在他怀里。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-092",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "梳妆台边",
    "text": "小怪兽站着靠在梳妆台，大大怪拿羽毛扫过她大腿内侧。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-093",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "枕头半遮",
    "text": "小怪兽拿枕头遮住上半身，大大怪隔着枕头揉捏她胸口。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-094",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "床尾跪趴",
    "text": "小怪兽跪趴在床尾，大大怪用手抚摸她的背部和臀线。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-095",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "落地窗前",
    "text": "两人站在落地窗前，大大怪从背后伸手解开小怪兽长裤。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-096",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "沙发靠背",
    "text": "小怪兽趴在沙发靠背上，大大怪站在背后解开她内衣。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-097",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "书桌桌面",
    "text": "小怪兽躺倒在书桌上，大大怪扯开她的上衣亲吻胸口。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-098",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "门框压迫",
    "text": "大大怪单手撑住门框，将小怪兽圈在怀里拉下衣服拉链。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-099",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "地板翻滚",
    "text": "两人拥抱着在卧室地板上翻滚半圈，玩家压在伴侣身上。",
    "rolePolicy": "dynamic",
    "source": "二阶段.txt"
  },
  {
    "id": "foreplay-scene-100",
    "stage": "foreplay",
    "stageLabel": "前戏",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "床铺中央",
    "text": "两人脱去上衣躺在床中央，大大怪侧身抚摸小怪兽胸口。",
    "rolePolicy": "fixed",
    "source": "二阶段.txt"
  },
  {
    "id": "deepening-directed-001",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "手部套弄",
    "text": "小怪兽用手握住大大怪的私密处，上下套弄60秒。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-002",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "边缘打圈",
    "text": "大大怪用指腹在小怪兽私密处外部打圈刺激60秒。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-003",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "玩具震动",
    "text": "玩家拿着震动跳蛋，贴在伴侣私密处外部震动60秒。",
    "rolePolicy": "dynamic",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-004",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "口部舔舐",
    "text": "大大怪低头，用舌头舔舐小怪兽的敏感部位60秒。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-005",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "胸部夹击",
    "text": "小怪兽用双乳夹住大大怪的私密处，上下摩擦60秒。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-006",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "大腿摩擦",
    "text": "小怪兽用大腿内侧夹住大大怪的私密处，来回摩擦。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-007",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "舌尖拨动",
    "text": "大大怪用舌尖快速拨动小怪兽的敏感点，持续30秒。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-008",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "手指浅入",
    "text": "大大怪将一根手指探入小怪兽体内，缓慢抽动30秒。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-009",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "冰口吞咽",
    "text": "小怪兽含一口冰水，低头为大大怪口部服务30秒。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-010",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "骑脸摩擦",
    "text": "小怪兽跨坐在大大怪脸上，隔着内裤前后摩擦60秒。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-011",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "掌心搓揉",
    "text": "玩家倒满润滑液，用手掌大面积搓揉伴侣的私密处边缘。",
    "rolePolicy": "dynamic",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-012",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "玩具游走",
    "text": "大大怪拿着震动棒，在小怪兽大腿根部和洞口游走。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-013",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "吸吮敏感",
    "text": "玩家用嘴唇包住伴侣的敏感点，用力吸吮15秒。",
    "rolePolicy": "dynamic",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-014",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "手口并用",
    "text": "小怪兽单手套弄大大怪的根部，同时低头舔舐顶端。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-015",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "深入扩张",
    "text": "大大怪用两根手指进入小怪兽体内，轻轻撑开内壁。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-016",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "会阴按压",
    "text": "玩家在用口服务时，伸出一根手指按压伴侣的会阴处。",
    "rolePolicy": "dynamic",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-017",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "隔裤挑逗",
    "text": "玩家握住伴侣隔着内裤的私密处，用力揉捏30秒。",
    "rolePolicy": "dynamic",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-018",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "臀沟舔舐",
    "text": "大大怪从背后靠近，用舌尖舔舐小怪兽的臀沟边缘。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-019",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "跨坐套弄",
    "text": "小怪兽跨坐在大大怪腿上，自己伸手套弄他的私密处。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-020",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "乳首吸吮",
    "text": "大大怪含住小怪兽的胸前红点，用力吸吮并用舌尖打圈。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-021",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "快速指法",
    "text": "大大怪加快手指在小怪兽体内的抽动频率，持续30秒。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-022",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "根部抓握",
    "text": "小怪兽紧紧握住大大怪的根部，减慢套弄的速度30秒。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-023",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "玩具按压",
    "text": "小怪兽拿着玩具，用力按压在自己的敏感点上展示。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-024",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "洞口摩擦",
    "text": "大大怪握住自己的私密处，在小怪兽洞口外侧来回摩擦。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-directed-025",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "唇边游走",
    "text": "小怪兽将大大怪的私密处贴在自己嘴唇边，不张嘴只摩擦。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-026",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "浅入摩擦",
    "text": "大大怪手指浅入，小怪兽主动扭腰配合手指摩擦。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-027",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "双腿夹紧",
    "text": "小怪兽用双腿夹住大大怪的手，大大怪伸手揉她胸口。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-028",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "暂停确认",
    "text": "玩家在伴侣快到顶点时停手，伴侣口头说出“继续”。",
    "rolePolicy": "dynamic",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-029",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "脸部跨坐",
    "text": "小怪兽跨坐在大大怪脸上，大大怪用舌头向上舔舐。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-030",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "速度指挥",
    "text": "大大怪加快套弄速度，小怪兽通过喊“快或慢”调整。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-031",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "强行按压",
    "text": "玩家帮伴侣口侍，伴侣双手按住玩家的头往下压。",
    "rolePolicy": "dynamic",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-032",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "张开双腿",
    "text": "大大怪轻拍小怪兽大腿内侧，小怪兽主动将双腿大张。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-033",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "挺胸迎合",
    "text": "大大怪揉捏小怪兽胸部，小怪兽主动挺起胸膛迎合。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-034",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "拔出催促",
    "text": "大大怪抽出手指不动，小怪兽大声说“我想你进来”。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-035",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "按手制止",
    "text": "玩家动作过于猛烈，伴侣按住玩家的手腕强制暂停10秒。",
    "rolePolicy": "dynamic",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-036",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "引导抚摸",
    "text": "小怪兽握住大大怪的手指，引导他按压自己最敏感的点。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-037",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "索要亲吻",
    "text": "玩家在下方口侍，伴侣拉起玩家的脸回馈一个深吻。",
    "rolePolicy": "dynamic",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-038",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "臀部抬高",
    "text": "大大怪轻拍小怪兽臀部，小怪兽趴在床上主动抬高腰部。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-039",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "玩具替换",
    "text": "玩家拿走伴侣的玩具，伴侣立刻张开腿要求玩家用手。",
    "rolePolicy": "dynamic",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-040",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "收缩内壁",
    "text": "大大怪手指停在小怪兽体内不动，小怪兽用力收缩夹紧。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-041",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "靠近索取",
    "text": "大大怪摩擦洞口不进，小怪兽用双手抓住他往里按。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-042",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "深喉挑战",
    "text": "小怪兽尝试含入更深，大大怪摸着她的头发安抚。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-043",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "抬腿挂肩",
    "text": "大大怪站立，小怪兽主动将双腿挂在他的肩膀上。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-044",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "求饶暂停",
    "text": "玩家猛烈刺激伴侣敏感点，直到伴侣大声说受不了才停。",
    "rolePolicy": "dynamic",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-045",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "吞咽润滑",
    "text": "玩家将润滑液滴在伴侣胸口，伴侣伸手抹开并挺起腰。",
    "rolePolicy": "dynamic",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-046",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "跨坐扭动",
    "text": "小怪兽跨坐压住大大怪的手，大大怪配合她扭动的节奏。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-047",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "后仰支撑",
    "text": "大大怪舔舐小怪兽，小怪兽双手向后撑住床铺大口喘气。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-048",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "夹紧手指",
    "text": "大大怪抽出手指，小怪兽双腿用力夹紧他的手腕不松开。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-049",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "舔唇暗示",
    "text": "小怪兽舔舐自己的嘴唇，大大怪立刻低头吻住她的嘴。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-response-050",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "加重力道",
    "text": "玩家捏住伴侣的大腿，伴侣口头要求玩家再用点力揉捏。",
    "rolePolicy": "dynamic",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-051",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互相口侍",
    "text": "两人采用69姿势，同时为对方进行口部服务60秒。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-052",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "手部互碰",
    "text": "两人面对面侧躺，同时用手抚摸对方的私密处60秒。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-053",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "冰火交替",
    "text": "两人分别含一口冰水和温水，交替亲吻对方大腿内侧。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-054",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "洞口摩擦",
    "text": "两人私密处互相贴紧，不上滑只在洞口摩擦60秒。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-055",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "同频喘息",
    "text": "两人在互相刺激的过程中，调整呼吸节奏直到完全一致。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-056",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互探深浅",
    "text": "两人同时伸出一根手指，探入对方体内的敏感部位。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-057",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "眼神锁定",
    "text": "两人一边用手套弄对方，一边全程保持对视不躲闪。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-058",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "十指互扣",
    "text": "两人双手十指紧扣压在头顶，用下半身紧贴着缓慢摩擦。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-059",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "唇齿相依",
    "text": "两人保持深吻状态，双手在对方私密处快速游走刺激。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-060",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互摸胸口",
    "text": "两人赤裸上身，双手互相揉捏对方的胸部和红点。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-061",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互抹润滑",
    "text": "两人把润滑液倒在手上，互相涂抹在对方的私密处边缘。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-062",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "腿部交缠",
    "text": "两人面对面拥抱，大腿互相交缠用力摩擦对方的私密处。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-063",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互相指引",
    "text": "两人握住对方的手，带着对方触摸自己最敏感的位置。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-064",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "同步加速",
    "text": "两人用手抚摸对方时，同时加快动作频率冲刺30秒。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-065",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互相挑逗",
    "text": "两人都不碰重点，只在对方私密处周围三厘米处画圈。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-066",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互吻大腿",
    "text": "两人呈69姿势，但不碰私密处，只狂热亲吻大腿内侧。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-067",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "暂停共吸",
    "text": "两人同时停止手上的动作，拥抱在一起深呼吸平复30秒。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-068",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互捏臀部",
    "text": "两人紧紧贴合，双手伸到对方身后用力揉捏臀部肌肉。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-069",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "交换唾液",
    "text": "两人接吻时，故意将口水哺喂给对方，并发出水渍声。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-070",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互吹凉气",
    "text": "两人对着对方湿润的私密处轻轻吹气，感受凉意。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-071",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互相摩擦",
    "text": "两人全身赤裸紧贴，用身体的每一寸肌肤来回摩擦。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-072",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "玩具互换",
    "text": "两人各自拿着一个玩具，同时放在对方的敏感点上震动。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-073",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互掐腰侧",
    "text": "两人同时用双手掐住对方的腰侧，用力往自己怀里按。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-074",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "舌尖互探",
    "text": "两人互相舔舐对方的嘴唇，并把舌头探入对方口中搅动。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-duo-075",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "同步爽感",
    "text": "两人在边缘试探时，同时用一句话说出现在的爽感。",
    "rolePolicy": "none",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-076",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "浴缸服务",
    "text": "大大怪躺在浴缸里，小怪兽跪在边缘为他口部服务。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-077",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "镜前张腿",
    "text": "小怪兽在穿衣镜前张开双腿，大大怪蹲下手指进入。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-078",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "床头跪趴",
    "text": "小怪兽手扶床头跪趴，大大怪在背后用玩具刺激她。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-079",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "枕垫腰部",
    "text": "小怪兽平躺，大大怪把枕头垫在她腰下，低头口侍。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-080",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "沙发边缘",
    "text": "小怪兽坐在沙发边缘张开腿，大大怪跪在地上舔舐。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-081",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "书桌跨坐",
    "text": "大大怪靠坐书桌，小怪兽跨坐他腿上，大大怪揉她胸。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-082",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "飘窗后入",
    "text": "小怪兽趴在飘窗上，大大怪站在背后用手指探入她体内。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-083",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "洗手台上",
    "text": "小怪兽坐在洗手台上，大大怪挤出洗手液涂抹她大腿。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-084",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "电脑椅上",
    "text": "大大怪坐电脑椅上，小怪兽跪在地毯上解开他裤子口侍。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-085",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "地板平躺",
    "text": "大大怪平躺在木地板上，小怪兽骑在他腰上隔裤摩擦。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-086",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "门后站立",
    "text": "小怪兽靠在门后抬起一条腿，大大怪用手抚摸她私密处。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-087",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "餐桌仰躺",
    "text": "小怪兽仰躺在餐桌上，大大怪低头吸吮她的胸部红点。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-088",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "衣柜镜前",
    "text": "两人站在衣柜全身镜前，大大怪从身后伸手揉捏她胸口。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-089",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "床尾地毯",
    "text": "小怪兽坐在地毯上靠着床尾，大大怪双手托住她的腰摩擦。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-090",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "换鞋凳前",
    "text": "大大怪坐在换鞋凳上，小怪兽单膝跪地用手套弄他。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-091",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "阳台窗前",
    "text": "小怪兽背靠阳台玻璃，大大怪低头亲吻她大腿根部。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-092",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "靠墙深蹲",
    "text": "小怪兽背靠墙壁深蹲，大大怪拿玩具按在她敏感点上。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-093",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "沙发靠背",
    "text": "小怪兽趴在沙发靠背上，大大怪从后面用手分开她双腿。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-094",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "电视柜旁",
    "text": "大大怪靠在电视柜旁，小怪兽低头双手握住他根部舔舐。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-095",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "枕头捂脸",
    "text": "小怪兽平躺拿枕头捂住脸，大大怪用手指在她体内抽动。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-096",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "椅子反坐",
    "text": "小怪兽反坐在椅子上抱住椅背，大大怪在背后揉捏她臀部。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-097",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "墙角抬腿",
    "text": "大大怪在墙角抬起小怪兽的一条腿，低头用力吸吮大腿内侧。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-098",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "床垫边缘",
    "text": "大大怪平躺在床垫边缘，小怪兽跨坐在他胸口揉他头发。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-099",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "浴室花洒",
    "text": "两人站在花洒下，大大怪就着热水用手指扩张小怪兽内壁。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "deepening-scene-100",
    "stage": "deepening",
    "stageLabel": "深入",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "茶几桌面",
    "text": "小怪兽坐在茶几上，大大怪分开她双腿低头埋在中间。",
    "rolePolicy": "fixed",
    "source": "三阶段.txt"
  },
  {
    "id": "finale-directed-001",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "传教士位",
    "text": "大大怪让小怪兽仰躺，抬起她双腿直接进入60秒。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-002",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "女方上位",
    "text": "小怪兽跨坐在大大怪身上，双手扶胸上下起伏60秒。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-003",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "背后进入",
    "text": "小怪兽跪趴，大大怪从背后进入，快速抽插60秒。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-004",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "侧卧结合",
    "text": "大大怪从小怪兽身后侧卧进入，双手抱紧她缓慢抽动。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-005",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "抬腿深入",
    "text": "大大怪将小怪兽的双腿架在肩膀上，进行最深处捣弄60秒。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-006",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "骑乘画圈",
    "text": "小怪兽在上位停止起伏，改为扭动腰肢画圈研磨60秒。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-007",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "背后浅插",
    "text": "大大怪在后入姿势下，只在洞口三分之一处浅浅抽动60秒。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-008",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "极限冲刺",
    "text": "大大怪按住小怪兽的胯骨，用最快速度连续冲刺30秒。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-009",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "慢速拔出",
    "text": "大大怪缓慢抽出直到快离开，再用极慢的速度整根没入。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-010",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "仰躺迎合",
    "text": "小怪兽仰躺在下方，双手抱住大大怪的脖子主动向上挺腰。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-011",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "反向骑乘",
    "text": "小怪兽背对大大怪跨坐，双手向后撑住他的大腿起伏60秒。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-012",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "揉胸抽插",
    "text": "大大怪在传教士姿势下，一边快速抽动一边揉捏她胸部。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-013",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "拍打臀部",
    "text": "大大怪在后入姿势下，配合抽插频率清脆拍打小怪兽臀部。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-014",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "停顿碾压",
    "text": "大大怪进入到底部不动，用力向上碾压小怪兽的敏感点15秒。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-015",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "剪刀交叠",
    "text": "小怪兽平躺，双腿紧紧夹住大大怪的腰，大大怪动腰抽插。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-016",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "站立抬腿",
    "text": "大大怪站立，抬起小怪兽的一条腿架在自己腰上进入60秒。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-017",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "跪姿下压",
    "text": "小怪兽跪坐在大大怪身上，双手按住他胸肌用力向下坐。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-018",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "蝴蝶张开",
    "text": "小怪兽仰躺，双脚脚心相对大张，大大怪从正上方压迫进入。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-019",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "玩具辅助",
    "text": "大大怪在结合抽插的同时，单手拿着跳蛋按在小怪兽外部。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-020",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "捏下巴吻",
    "text": "大大怪在结合时捏住小怪兽的下巴，强硬地深吻她30秒。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-021",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "俯身贴合",
    "text": "小怪兽在上位完全俯身趴在大大怪胸口，小幅度研磨60秒。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-022",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "侧臀后入",
    "text": "小怪兽侧躺，大大怪抬起她上方的一条腿，从侧后方进入。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-023",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "拔出游走",
    "text": "大大怪完全拔出，在小怪兽腿心游走摩擦15秒后再深插。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-024",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "贴耳喘息",
    "text": "大大怪后入时整个上半身压在小怪兽背上，贴着她耳朵喘息。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-directed-025",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "directed",
    "modeLabel": "主动卡",
    "title": "按肩发力",
    "text": "小怪兽反向跨坐，双手按住大大怪的膝盖，借力上下起伏。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-026",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "上顶配合",
    "text": "小怪兽上位起伏30秒，大大怪双手扶腰主动向上顶弄。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-027",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "向后迎合",
    "text": "大大怪后入抽插，小怪兽随着节奏向后撅起臀部迎合。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-028",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "停顿催促",
    "text": "大大怪快速冲刺10秒后停止，小怪兽出声催促他继续。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-029",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "收缩夹紧",
    "text": "大大怪深入到底部静止，小怪兽用力收缩内壁夹紧15秒。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-030",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "换姿指令",
    "text": "小怪兽要求换成传教士姿势，大大怪立刻抽出配合转身。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-031",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "抓背反馈",
    "text": "大大怪加快抽插速度，小怪兽双手用力抓挠他的后背。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-032",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "快慢指挥",
    "text": "小怪兽喊“快”或“慢”，大大怪必须完全遵照指令抽插。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-033",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "搂脖索吻",
    "text": "大大怪俯身冲刺，小怪兽勾住他脖子主动抬起下巴索吻。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-034",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "深浅控制",
    "text": "大大怪浅插挑逗，小怪兽用双腿夹住他的腰强制拉向深处。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-035",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "咬肩承受",
    "text": "大大怪用力捣弄深处，小怪兽张嘴咬住他的肩膀承受撞击。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-036",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "摸胸请求",
    "text": "小怪兽在下方主动拉过大大怪的手，按在自己胸部要求揉捏。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-037",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "后靠支撑",
    "text": "小怪兽跨坐起伏感到累向后靠，大大怪抱住她主动动腰。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-038",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "九浅一深",
    "text": "大大怪按浅九深一抽插，小怪兽在深入那下大声叫出来。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-039",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "拔出抗议",
    "text": "大大怪故意拔出退开，小怪兽拉住他的手臂要求立刻进来。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-040",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "夹腰锁定",
    "text": "大大怪准备抽出，小怪兽双腿死死锁住他的腰不让离开。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-041",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "咬唇回应",
    "text": "大大怪低头亲吻，小怪兽用力吸吮他的下嘴唇并扭动腰肢。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-042",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "顶点倒数",
    "text": "小怪兽感觉快到顶点倒数五秒，大大怪配合全速冲刺。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-043",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "抬臀方便",
    "text": "大大怪拍拍小怪兽的腰，小怪兽立刻塌腰翘臀方便后入。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-044",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "迎合撞击",
    "text": "大大怪站立抱起小怪兽进入，小怪兽双腿盘腰迎合撞击。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-045",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "语言反馈",
    "text": "大大怪用力抽插，小怪兽大声说出现在的深度和舒服位置。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-046",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "按手放慢",
    "text": "大大怪撞击太深，小怪兽按住他腹部要求放慢速度10秒。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-047",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "贴面压倒",
    "text": "小怪兽在上位俯身抱紧大大怪，大大怪顺势翻身将她压住。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-048",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "汗水交融",
    "text": "大大怪汗水滴在小怪兽胸口，小怪兽伸手抹匀并主动挺胸。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-049",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "释放提示",
    "text": "大大怪提示即将释放，小怪兽用力抱紧他承受最后冲刺。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-response-050",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "response",
    "modeLabel": "回应卡",
    "title": "索要拥抱",
    "text": "完成释放后大大怪趴下，小怪兽张开双臂紧紧拥抱他后背。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-051",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "十指起伏",
    "text": "传教士姿势下，两人十指紧扣，共同配合抽插起伏60秒。",
    "rolePolicy": "none",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-052",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "拔出冷却",
    "text": "两人停止结合完全拔出，互相紧抱静止平复呼吸30秒。",
    "rolePolicy": "none",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-053",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "侧卧共振",
    "text": "两人侧卧结合，大大怪动腰推进，小怪兽收缩内壁回应。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-054",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "坐姿交叠",
    "text": "两人面对面盘腿拥抱坐下，结合在一起缓慢深层画圈60秒。",
    "rolePolicy": "none",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-055",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互相接吻",
    "text": "两人在快速冲刺的结合中，同时张开嘴深深吻住对方30秒。",
    "rolePolicy": "none",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-056",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "同步高潮",
    "text": "两人沟通快感进度，调整频率努力同时到达最终的顶点。",
    "rolePolicy": "none",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-057",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "眼神锁定",
    "text": "两人在传教士姿势下，全程睁眼看着对方的眼睛抽插60秒。",
    "rolePolicy": "none",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-058",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "十字交叉",
    "text": "小怪兽平躺，大大怪侧身呈十字形进入，摩擦侧壁60秒。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-059",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "停顿共吸",
    "text": "结合的间隙大大怪停住不动，两人紧抱在一起深呼吸30秒。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-060",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互揉臀部",
    "text": "坐姿结合下，两人双手都环抱到对方身后，用力揉捏臀部。",
    "rolePolicy": "none",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-061",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "一起加速",
    "text": "两人同时发力，用最高频率疯狂撞击和向上迎合30秒。",
    "rolePolicy": "none",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-062",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "额头相抵",
    "text": "结合时两人低头额头抵住额头，感受每一次冲撞的震动。",
    "rolePolicy": "none",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-063",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "交换呼吸",
    "text": "大大怪每次深入时两人互相呼气，保持喘息频率完全一致。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-064",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互说情话",
    "text": "在抽插的最深处，两人同时对对方大声说一句我爱你。",
    "rolePolicy": "none",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-065",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "翻滚切换",
    "text": "两人保持结合状态不拔出，从大大怪在下直接翻滚到他在上。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-066",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "耳鬓厮磨",
    "text": "两人侧卧进入，脸颊贴在一起互相摩擦耳鬓抽动60秒。",
    "rolePolicy": "none",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-067",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "极致放慢",
    "text": "两人停止动作，用平时五分之一的极慢速度抽动一分钟。",
    "rolePolicy": "none",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-068",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "双腿交缠",
    "text": "面对面结合时，两人将大腿互相死死交缠锁住，不再分开。",
    "rolePolicy": "none",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-069",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "同频发声",
    "text": "随着每一次撞击，两人不憋着声音，同时大声叫出来。",
    "rolePolicy": "none",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-070",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "事后清理",
    "text": "结合释放后两人分开，大大怪拿湿纸巾帮小怪兽擦拭身体。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-071",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "温存相拥",
    "text": "一切结束后，两人拉过被子盖好，赤裸身体紧紧相拥五分钟。",
    "rolePolicy": "none",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-072",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互吻额头",
    "text": "释放之后平复心跳，两人同时抬头在对方额头上亲吻。",
    "rolePolicy": "none",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-073",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "互相喂水",
    "text": "激烈运动后，两人不用手只用嘴唇互相喂对方喝下一口水。",
    "rolePolicy": "none",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-074",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "按摩舒缓",
    "text": "两人轮流给对方刚才受力的腰部和腿部按摩揉捏一分钟。",
    "rolePolicy": "none",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-duo-075",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "duo",
    "modeLabel": "双人卡",
    "title": "紧贴入眠",
    "text": "清理完毕后，两人从背后勺子式抱在一起，身体完全贴合。",
    "rolePolicy": "none",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-076",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "镜前站立",
    "text": "两人在穿衣镜前站立后入60秒，全程看着镜中结合动作。",
    "rolePolicy": "none",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-077",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "椅子抽插",
    "text": "大大怪坐在椅子上，小怪兽跨坐进入，上下起伏抽插60秒。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-078",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "桌边后入",
    "text": "小怪兽扶住餐桌边缘站立，大大怪从后方进入抽动60秒。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-079",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "床沿悬空",
    "text": "小怪兽躺在床沿双腿踩地，大大怪站立进入冲刺60秒。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-080",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "沙发侧躺",
    "text": "两人在沙发上挤在一起侧卧结合，大大怪缓慢动腰60秒。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-081",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "洗手台抱",
    "text": "大大怪把小怪兽抱上洗手台边缘，站立分开她双腿进入。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-082",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "墙角压迫",
    "text": "大大怪把小怪兽按在墙角，托起她一条腿悬空进入抽插。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-083",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "门板后入",
    "text": "小怪兽双手撑在卧室门板上，大大怪从背后快速撞击。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-084",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "电脑椅转",
    "text": "小怪兽跨坐在电脑椅的大大怪身上，大大怪扶腰起伏。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-085",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "飘窗上位",
    "text": "大大怪躺在飘窗垫子上，小怪兽跨坐他腰上上下起伏。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-086",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "浴缸坐姿",
    "text": "两人面对面坐在空浴缸里，小怪兽跨坐在大大怪腿上结合。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-087",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "梳妆台前",
    "text": "小怪兽趴在梳妆台面上，大大怪在背后站立进入抽插。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-088",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "地毯后入",
    "text": "小怪兽跪趴在床尾地毯上，大大怪从背后进入快速抽插。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-089",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "换鞋凳坐",
    "text": "大大怪坐在换鞋凳上，小怪兽背对大大怪跨坐起伏60秒。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-090",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "窗帘遮挡",
    "text": "两人躲在落地窗帘后，大大怪托着小怪兽臀部站立结合。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-091",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "冰箱门边",
    "text": "小怪兽扶着关上的冰箱门，大大怪在背后进入快速抽动。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-092",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "电视柜靠",
    "text": "大大怪背靠电视柜坐在地上，小怪兽跨坐在他大腿上起伏。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-093",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "枕头垫腰",
    "text": "小怪兽平躺在床，腰下垫两个枕头抬高，大大怪冲刺进入。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-094",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "床头柜撑",
    "text": "小怪兽双手撑着床头柜弯腰，大大怪在背后掐住她腰进入。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-095",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "沙发靠背",
    "text": "小怪兽趴在沙发靠背上，大大怪站在沙发后方进入结合。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-096",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "淋浴房内",
    "text": "两人在淋浴房站立拥抱，热水冲刷下大大怪挺腰进入。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-097",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "被窝侧入",
    "text": "两人完全钻进被窝里，大大怪从小怪兽背后侧卧深插。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-098",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "阳台玻璃",
    "text": "小怪兽双手按在阳台玻璃上，大大怪从背后压紧她抽插。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-099",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "书桌桌面",
    "text": "小怪兽平躺在书桌上双腿大张，大大怪站在桌前进入。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  },
  {
    "id": "finale-scene-100",
    "stage": "finale",
    "stageLabel": "最终",
    "mode": "scene",
    "modeLabel": "场景卡",
    "title": "床尾悬空",
    "text": "小怪兽趴在床尾，上半身在床上下半身悬空，大大怪后入。",
    "rolePolicy": "fixed",
    "source": "四阶段.txt"
  }
] as const
